custom:
  var1: 2
  var2: 8

spring:
  output:
    ansi:
      enabled: ALWAYS
  logging:
    level:
      root: INFO
      com:
        example:
          logging_exercise:
            services: DEBUG